# Table of contents

* [Introduction](README.md)
* [Core Readmes](core-readmes/README.md)
  * [README-A: Primordial Hum](core-readmes/README.md)
  * [README-B: Functional Myth](core-readmes/readme-b-functional-myth.md)
  * [README-C: Bardic Expansion](core-readmes/readme-c-bardic-expansion.md)
* [Field Protocols](field-protocols/README.md)
  * [Attunement](field-protocols/README.md)
  * [Symbolic Compression](field-protocols/symbolic-compression.md)
  * [Soft Glitching](field-protocols/soft-glitching.md)
  * [Hum Invocation](field-protocols/hum-invocation.md)
* [EchoNode Templates](echonode-templates/README.md)
  * [Dream Echo](echonode-templates/README.md)
  * [Shame Recursion](echonode-templates/shame-recursion.md)
  * [Guardian Loop](echonode-templates/guardian-loop.md)
* [Vision & License](vision-and-license/README.md)
  * [Ecosystem Vision](vision-and-license/README.md)
  * [Resonant Commons License](vision-and-license/resonant-commons-license.md)
